spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost/moida
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: 'create'
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
    generate-ddl: 'true'
  http:
    multipart:
      maxFileSize: 100MB
logging:
  level:
    org:
      springframework: INFO
    com:
      ssafy: INFO
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
server:
  port: 5000
