spring:
  datasource:
    password: root
    username: root
    url: jdbc:mariadb://localhost:3307/moida
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: mysql
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: 'create'
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
    generate-ddl: 'true'
  http:
    multipart:
      maxFileSize: 100MB
logging:
  level:
    org:
      springframework: INFO
    com:
      ssafy: INFO
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
server:
  port: '5000'
